sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
before_install:
  - npm install -g npm@~1.4.28
before_script:
  - npm install -g istanbul grunt-cli
  - npm install coveralls
  - npm install git+https://github.com/node-red/node-red.git
  - export NODE_RED_HOME=`pwd`/node_modules/node-red
  - (cd $NODE_RED_HOME ; npm install nock@~0.48.0)
